# Tach STK_STRUCK RA THANH 1 FILE RIENG

SIZE_NUMBER = [8,10,12]

BUSINESS_TYPE = ["PERSONAL","BUSINESS"]

TYPE_STK = ["NORMAL", "VVIP"]

ARR_SAME_LOC_PHAT = [6,8,6]

MIRROR_TYPE = ["FULL","NONFULL"]

TEMP_COPARE_MIRROR = ["{A}{B}{B}","{A}{B}{C}{C}{B}"]

REPEAT_TYPE = ["FULL","NONFULL"]

NAME_STK = ['SAME',"CONTINOUS","THREE-THREE","FOUR-FOUR","FIVE-FIVE"
            ,"SIX-SIX","THREE-FOUR","MIRROR","REPEAT","LOC_PHAT","END_SIX_TO_NINE","END_SAME","END_SPECIAL"]

STRUCT_CODE = { 
    'STRUCTURE_CODE_08' : 8,
    'STRUCTURE_CODE_10' : 10,
    'STRUCTURE_CODE_12' : 12
}

INSERT_TYPE = ["HEAD","END","BETWEEN","BETWEEN_HEAD","BETWEEN_END","NON_MIRROR"]

TYPE_FOUR_FOUR_10 = ["ADJACENT","NO_ADJACENT"]

ARR_SPECIAL_NUMBER = [66,68,69,79,86,88,89,99]

